### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by veeara282** [vega/vega.github.io#11]
Nice to see you today, @arvind.

I don't see a license anywhere. Since this is a website, though, I would just add a footer link.

**Comment by domoritz** [comment]
Vega/Vega-Lite are under BSD license. I don't think it makes sense to put a license on the start page because the licenses of various projects may vary.

**Comment by veeara282** [comment]
The license would apply to the website, not the projects. [CC-BY](https://creativecommons.org/licenses/by/4.0/) works well for websites (as opposed to software).
