### ISSUE TITLE
Docs & Tutorials links of Vega & Vega-Lite point to Landing pages instead of their respective pages

### ISSUE THREAD

**Issue by na399** [vega/vega.github.io#20]
Hi there,

On the homepage (https://vega.github.io/), the Docs & Tutorials links of Vega & Vega-Lite point to their Landing pages instead of their respective Docs and Tutorials pages. I was wondering whether there are any deliberate reasons behind this.

I think it would be more user-friendly to separate Docs and Tutorials and link them to their own pages. What do you think?

Cheers,
Max

**Comment by domoritz** [comment]
I think the point was that we don't have a separate link for the "Website" (the image being a link is not very discoverable). 

I'm okay with changing the links, though. Do you want to send a PR to propose a change?

**Comment by na399** [comment]
I get your point, @domoritz. 

Once I've learned that the Docs & Tutorials can't bring me to the Docs I want to check, I usually click the image as I know that it will take me to the same page anyway. Also, the image is larger than the link. 😂

I can give it a go.

**Comment by domoritz** [comment]
Thank you for raising the issue and working on a PR.

**Comment by na399** [comment]
That's nothing compared to your and everyone's magnificent work on Vega! Thank you so much for developing it.

I'm working on the VAST Challenge. This is the first time I use Vega, which explains why I keep visiting the docs. I've just realized how powerful and flexible it is, yet so easy to use. I can't wait to publish my work and write a blog about Vega. ☺️

**Comment by domoritz** [comment]
Thank you for the kind words and you are very welcome.
