### ISSUE TITLE
Vega Lite Slack Invite-Link is no longer working

### ISSUE THREAD

**Issue by keckelt** [vega/vega.github.io#22]
The Slack [invite link](https://bit.ly/join-vega-slack) on the [Vega Lite Page](https://vega.github.io/vega-lite/#additional-links) is no longer active:

![image](https://user-images.githubusercontent.com/10337788/67866125-bbd3e300-fb28-11e9-9af7-c26c4bba08ee.png)

**Comment by domoritz** [comment]
Here is the working link: https://join.slack.com/t/vega-js/shared_invite/enQtMzg1ODUzMzM5OTcwLWE1Yzg2MGY0N2ZlMWIyMjM0MzY4OWZiZWExYTI3Y2JlNmFjZTEwMDAyMjA2ZTMwNmQ1ZWU0MzIzNWM2MzU1MDQ. 

@kanitw will update the bitly soon.

**Comment by domoritz** [comment]
We don't have a slack link on the website anymore.
