### ISSUE TITLE
Convert the page into React.js

### ISSUE THREAD

**Issue by abrehan2** [vega/vega.github.io#26]
Hi, I will convert the page in React.js and will use Chakra UI. Thanks.

## Demonstration of the page I will be working on:
![image](https://github.com/vega/vega.github.io/assets/100872683/74fda24b-00c7-4341-9ddf-71da7ba8c2d1)
![image](https://github.com/vega/vega.github.io/assets/100872683/6ee9d625-f46a-4d6a-b2c0-b51da9dcfe94)
![image](https://github.com/vega/vega.github.io/assets/100872683/de054198-394c-4901-91de-cbbfb2a9c5c9)

**Comment by domoritz** [comment]
Thanks for the issue. We don't really edit this page much and it's very lightweight so I don't think it's worth using a heave framework like react right now. There are other projects that need more help such as the Vega editor.
