### ISSUE TITLE
Landing page: replace 'vincent' by 'Altair'?

### ISSUE THREAD

**Issue by axel-tanner** [vega/vega.github.io#9]
Hi - I am new to vega.
As I am using python, I followed you link about 'vincent' as it is on your index page.
The author of vincent recommends though project altair (https://github.com/altair-viz/altair) instead, as he stopped to develop vincent further -> see https://github.com/wrobstory/vincent

Regards,
Axel

**Comment by domoritz** [comment]
Altair is built on top of Vega-Lite and we link to it at https://vega.github.io/vega-lite/usage/applications.html. I think the right thing is to remove the link to Vincent since it is deprecated.
